hydra:
  searchpath:
    - file://verl/verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  apply_chat_template_kwargs: {}

actor_rollout_ref:
  model:
    gradient_routing:
      enabled: false
      label_field: null
      label_subsample_rate: null
  rollout:
    engine_kwargs:
      vllm: {}

algorithm:
  adv_estimator: grpo_modified

  norm_adv_by_std_in_grpo: true
  fill_nan_global: true

  # Screening specs
  screening_specs: {} # WARNING: Dict fields are merged

  # Fields to pass to screening functions
  extra_infos: [] # WARNING: List fields are merged

reward_model:
  # Acts the same as batch if no activations are passed
  reward_manager: batch_activations

  # Custom reward function path is not used
  reward_kwargs: 
      reward_specs: {} # WARNING: Dict fields are merged


trainer:
  val_before_train: false
  debug_oom: false

activation_cache:
  enabled: False
  layers: [] # WARNING: List fields are merged
  position: "response_avg"
  batch_size: 16